- name: release:major
  color: 'ff0000'
  description: 'Major version bump (breaking changes)'

- name: release:minor
  color: 'ff9900'
  description: 'Minor version bump (new features)'

- name: release:patch
  color: '00ff00'
  description: 'Patch version bump (bug fixes)'

- name: bug
  color: 'd73a4a'
  description: 'Something isn''t working'

- name: enhancement
  color: 'a2eeef'
  description: 'New feature or request'

- name: documentation
  color: '0075ca'
  description: 'Improvements or additions to documentation'

- name: dependencies
  color: '0366d6'
  description: 'Pull requests that update a dependency file'

- name: skip-release
  color: 'cccccc'
  description: 'Skip creating a release for this PR'

